apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: evaluation-service
  namespace: argocd
spec:
  project: default
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: evaluation-secret
      namespace: ns-evaluation
      jsonPointers:
        - /data
        - /stringData
  source:
    repoURL: https://github.com/VianaCoder/togglemaster-monorepo.git
    targetRevision: main
    path: gitops/services/evaluation-service
  destination:
    server: https://kubernetes.default.svc
    namespace: ns-evaluation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
