apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: targeting-service
  namespace: argocd
spec:
  project: default
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: targeting-secret
      namespace: ns-targeting
      jsonPointers:
        - /data
        - /stringData
  source:
    repoURL: https://github.com/VianaCoder/togglemaster-monorepo.git
    targetRevision: main
    path: gitops/services/targeting-service
  destination:
    server: https://kubernetes.default.svc
    namespace: ns-targeting
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
