apiVersion: v1
kind: Namespace
metadata:
  name: ns-auth
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-flag
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-targeting
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-evaluation
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-analytics
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    # Allow kube-prometheus-stack to discover ServiceMonitors in this namespace
    prometheus: kube-prometheus
